---
- name: ensure config file is restored from backup
  copy:
    src: "{{ nextcloud_restore_config }}"
    dest: "{{ nextcloud_config_directory }}/config.php"
    remote_src: yes
    owner: "{{ nextcloud_web_user }}"
    group: "{{ nextcloud_web_user }}"
    mode: 0640
  when: "nextcloud_restore_config is defined and nextcloud_installed != true"
  register: nextcloud_restored_config
  tags: nextcloud.php.config

- name: ensure nextcloud database connection is configured
  template:
    src: database.config.php.j2
    dest: "{{ nextcloud_config_directory }}/database.config.php"
    owner: "{{ nextcloud_web_user }}"
    group: "{{ nextcloud_web_user }}"
    mode: 0640
  tags: nextcloud.php.config
  
- name: ensure nextcloud is configured
  template:
    src: custom.config.php.j2
    dest: "{{ nextcloud_config_directory }}/custom.config.php"
    owner: "{{ nextcloud_web_user }}"
    group: "{{ nextcloud_web_user }}"
    mode: 0640
  tags: nextcloud.php.config