---
- name: ensure database for nextcloud exists
  mysql_db:
    name: "{{ nextcloud_database_name }}"
    encoding: utf8
    collation: utf8_general_ci
  register: nextcloud_database

- name: ensure database user for nextcloud exists
  mysql_user:
    name: "{{ nextcloud_database_username }}"
    host: localhost
    password: "{{ nextcloud_database_password }}"
    priv: "{{ nextcloud_database_name }}.*:ALL"

- name: check database backup file
  stat:
    path: "{{ nextcloud_restore_database }}"
  register: nextcloud_database_backup_file
  when: nextcloud_restore_database is defined

- name: import nextcloud database from backup
  mysql_db:
    name: "{{ nextcloud_database_name }}"
    state: import
    target: "{{ nextcloud_restore_database }}"
  when: "nextcloud_database|changed and nextcloud_restore_database is defined and nextcloud_database_backup_file.stat.exists"
