---
# Only overrided variables should be here, 
# otherwise, use defaults:

# php_enablerepo: extras,centosplus

php_packages: 
# Basic
# Owncloud recommended:  
  - php-json
  - php-curl
  - php-posix

# Hash of name: and repo: to install packages from external repos liste above
external_packages:
  - { name: php-mcrypt, repo: epel }
  - { name: php-imagick, repo: remi }
  - { name: php55, repo: centos-sclo-rh }
  - { name: php55-php, repo: centos-sclo-rh }
  - { name: php55-php-gd, repo: centos-sclo-rh }
  - { name: php55-php-mbstring, repo: centos-sclo-rh }
  - { name: php55-php-mysqlnd, repo: centos-sclo-rh }
  - { name: php55-php-fpm, repo: centos-sclo-rh }
  - { name: php55-php-common, repo: centos-sclo-rh }
  - { name: php55-php-devel, repo: centos-sclo-rh }
  - { name: php55-php-cli, repo: centos-sclo-rh }
  - { name: php55-php-xml, repo: centos-sclo-rh }
  - { name: php55-php-intl, repo: centos-sclo-rh }
# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: true

# PHP-FPM configuration.
php_enable_php_fpm: true
php_fpm_listen: "/var/run/php5-fpm.sock"


php_memory_limit: "512M"
php_date_timezone: "Europe/Madrid"

php_error_logfile: "/var/log/php-errors.log"

# Cache
# opcache
php_opcache_enabled_in_ini: false
php_opcache_enable: "0"
php_opcache_enable_cli: "0"

# APC
php_enable_apc: false
php_apc_enabled_in_ini: false
php_apc_cache_by_default: "1"
php_apc_shm_size: "200M"
php_apc_stat: "1"
php_apc_enable_cli: "1"