---

- name: Creating users for given environment
  user: name={{item.key}} groups={{item.value.groups|join(',')}} append=yes shell=/bin/bash
  with_dict: "{{users}}"
  register: user_changed
  when: ( "'{{item.value.server_group}}' in group_names" or "'all' in {{item.value.server_group}}") and (local_users.stdout.find('{{item.key}}')==-1)
  tags: debug1

- name: Adding SSH key for given users
  authorized_key: user={{item.key}} key="{{item.value.ssh_key}}"
  with_dict: "{{users}}"
  when: ( "'{{item.value.server_group}}' in group_names" or "'all' in {{item.value.server_group}}") and (local_users.stdout.find('{{item.key}}')==-1)

- name: fix home folder permissions for new users
  file: path=/home/{{item.key}}/ owner={{item.key}} group={{item.key}} recurse=yes
  with_dict: "{{users}}"
  when: ( "'{{item.value.server_group}}' in group_names" or "'all' in {{item.value.server_group}}") and (local_users.stdout.find('{{item.key}}')==-1)

- name: copy default .bashrc for new users
  template: src=bashrc.j2 dest=/home/{{item.key}}/ force=no
  with_dict: "{{users}}"
  when: ( "'{{item.value.server_group}}' in group_names" or "'all' in {{item.value.server_group}}") and (local_users.stdout.find('{{item.key}}')==-1)
