---


- name: debug1
  debug: msg="Creating user {{item.key}} with groups {{item.value.groups}}"
  with_dict: "{{users}}"
  when: ("{{env}}" in {{item.value.server_group}}) or {{item.value.server_group}}==['all']
  tags: debug


- debug: msg="Inserting {{item.ssh_key}}"
  with_items: users
  when: ("{{env}}" in {{item.value.server_group}}) or {{item.value.server_group}}==['all']
  tags: debug


- debug: msg="{{item.name}} found, it will be deleted because {{env}} or 'all' is not {{item.value.server_group}}"
  with_items: users
  when: (local_users.stdout.find('{{item.name}}')!=-1) and ("{{env}}" not in {{item.value.server_group}}) and ('all' not in "{{item.value.server_group}}")
