
# Delete users in the user list that don't belong to this environment

- name: Make sure CL users not listed for this env are removed.
  user: name={{item.key}} state=absent remove=yes
  with_dict: "{{users}}"
  when: (local_users.stdout.find('{{item.key}}')!=-1) and ("{{env}}" not in {{item.value.env}}) and ('all' not in "{{item.value.env}}")

- name: Remove home directory
  file: state=absent dest=/home/{{item.key}}
  with_dict: "{{users}}"
  when: (local_users.stdout.find('{{item.key}}')!=-1) and ("{{env}}" not in {{item.value.env}}) and ('all' not in "{{item.value.env}}")

## Delete other users present in the machine that are not in the users list (except 'ubuntu')

- name: Remove any other users not present at all in the list
  user: name={{item}} state=absent remove=yes
  with_items: local_users.stdout_lines
  when: ("{{item}}" not in "{{users}}") and ("{{item}}" != "ubuntu") and ("{{item}}" != "nagios") and ("{{item}}" != "cht_agent")
  tags: debug

- name: Remove home directory
  file: state=absent dest=/home/{{item}}
  with_items: local_users.stdout_lines
  when: ("{{item}}" not in "{{users}}") and ("{{item}}" != "ubuntu") and ("{{item}}" != "nagios")

