---
galaxy_info:
  author: "Guillermo Perez"
  license: FreeBSD
  min_ansible_version: 1.9
 
  platforms:
  - name: EL
    versions:
      - 7
  - name: GenericBSD
    versions:
      - all
  - name: GenericLinux
    versions:
      - all
  - name: Debian
    versions:
      - all
      - etch
      - lenny
      - squeeze
      - wheezy
  #
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
    - web
dependencies: []
