---
dependencies: []

galaxy_info:
  author: Guillermo Perez
  original_author: geerlingguy
  description: PHP for RedHat/CentOS/Debian/Ubuntu.
  company: "Hispacloud"
  license: "GPLv3"
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
    - web

allow_duplicates: yes
