---

- name: Install additional repos (CentOS)
  package: name={{ item.url }} state=present
  with_items: "{{ additional_repos }}"

- name: Disable additional repos enabled by default
  command: yum-config-manager --disable "{{ item.name }}"*
  with_items: "{{ additional_repos }}"

- name: Ensure officially available PHP packages are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ php_packages }}"
  notify: restart webserver
  tags: install-php

- name: Install other packages from external repos
  package:
    name: "{{ item.name }}"
    state: installed
    enablerepo: "{{ item.repo }}"
  with_items: "{{ external_packages }}"

