- hosts: localhost
  roles:
    - role: openstack/create_instance
      tags: instance
  vars:
    instance_security_group: portal_hispacloud
    instance_size: 589
    instance_network: ext-net
  vars_prompt:
    - name: "instance_hostname"
      prompt: "Hostname for your new server: "
      
- hosts: nextcloud-aio
  roles:
    - role: openstack/create_volume
      tags: volume
  become: yes
