## Install owncloud node

- hosts: owncloud:mysql
  become: yes
  become_user: root
  roles:
    - provisioning/minimal_packages
    - provisioning/deploy_users
    - provisioning/sysconfig

- hosts: mysql
  become: yes
  become_user: root
  roles:
    - mariadb

- hosts: owncloud
  become: yes
  become_user: root
  roles:
    - nginx
    - php
    #- { role: ssl-certs, tags: ssl}
    - { role: owncloud, tags: owncloud }
