---
- name: check nextcloud installation
  stat:
    path: "{{ nextcloud_root_directory }}/occ"
  register: nextcloud_command

- debug: var=nextcloud_web_user

- name: get installation status of nextcloud
  shell: php {{ nextcloud_root_directory }}/occ status | grep install
  become: yes
  become_user: "{{ nextcloud_web_user }}"
  when: "nextcloud_command.stat.exists"
  changed_when: false
  register: nextcloud_status_installed

- name: get installed nextcloud version
  shell: php {{ nextcloud_root_directory }}/occ status | grep versionstring
  become: yes
  become_user: "{{ nextcloud_web_user }}"
  when: "nextcloud_command.stat.exists"
  changed_when: false
  register: nextcloud_status_version

- set_fact:
    nextcloud_installed: "{% if nextcloud_command.stat.exists %}{{ nextcloud_status_installed.stdout | regex_replace('.*installed: (?P<flag>.*)', '\\g<flag>') }}{% else %}false{% endif %}"
    nextcloud_installed_version: "{% if nextcloud_command.stat.exists and not (nextcloud_restored_config is defined and nextcloud_restored_config|changed) %}{{ nextcloud_status_version.stdout | regex_replace('.*versionstring: (?P<version>.*)', '\\g<version>') | replace(' ', '') }}{% endif %}"

- debug:
    var: nextcloud_installed
- debug:
    var: nextcloud_installed_version
