---
galaxy_info:
  original_author: mjanser
  author: Guillermo Perez
  description: Installs nextcloud on Fedora
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
    - name: Fedora
      versions:
        - 23
    - name: EL
      versions:
        - 7
    - name: CentOS
      versions:
        - 7    
  categories:
    - web
    - cloud
