---
- name: ensure owncloud cron job is installed
  cron:
    name: "owncloud cron"
    cron_file: owncloud
    user: "{{ owncloud_web_user }}"
    minute: "*/15"
    job: "php -f {{ owncloud_root_directory }}/cron.php"
