---
- name: ensure main directory has correct permissions
  file:
    path: "{{ owncloud_root_directory }}"
    state: directory
    owner: root
    group: "{{ owncloud_web_user }}"
    recurse: yes

  # when: "owncloud_download|changed"

- name: ensure other directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owncloud_web_user }}"
    group: "{{ owncloud_web_user }}"
    recurse: yes
  with_items:
    - "{{ owncloud_root_directory }}/apps"
    - "{{ owncloud_root_directory }}/apps-store"
    - "{{ owncloud_root_directory }}/themes"
    - "{{ owncloud_root_directory }}/assets"
    - "{{ owncloud_root_directory }}/config"
    - "{{ owncloud_data_directory }}"
- name: make sure /var/lib/php/session is owned by nginx
  file:
    dest: /var/lib/php/session
    state: directory
    owner: "{{ owncloud_web_user }}"
    group: "{{ owncloud_web_user }}"

- name: make sure .htaccess are created
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ owncloud_web_user }}"
    group: "{{ owncloud_web_user }}"
  with_items:
    - "{{ owncloud_root_directory }}/.htaccess"
    - "{{ owncloud_data_directory }}/.htaccess"

- name: apply owncloud's permission hardening script
  script: fixpermissions.sh "{{ owncloud_root_directory }}" "{{ owncloud_web_user }}"