---
# - set_fact:
#     owncloud_download_path: "{% if owncloud_release_channel == 'testing' %}/testing{% endif %}"
- name: create owncloud directory
  file:
    state: directory
    path: "{{ owncloud_root_directory }}"
    owner: root
    group: "{{ owncloud_web_user }}"

- name: ensure owncloud is installed
  unarchive:  
    src: "{{ owncloud_tarball_url }}{{ owncloud_version }}.{{ owncloud_tarball_extension }}"
    dest: "{{ nginx_root_directory }}"
    copy: no
  when: "owncloud_installed != true or owncloud_installed_version != owncloud_version"
  register: owncloud_download


# - name: cleanup github files
#   file:
#     path: "{{ owncloud_root_directory }}/{{ item }}"
#     state: absent
#   with_items: 
#     - .idea
#     - build
#     - tests
#     - .bowerrc
#     - .gitignore
#     - .gitmodules
#     - .jshintrc
#     - .mailmap
#     - .mention-bot
#     - .srcutinizer.yml
#     - .travis.yml
#     - autotest.sh
#     - autotest-external.sh
#     - autotest-hhvm.sh
#     - autotest-js.sh
#     - bower.json
#     - buildjsdocs.sh
#     - composer.json
#     - CONTRIBUTING.md
#     - COPYING-README
#     - issue_template.md
#     - README.md
    