---
# - set_fact:
#     owncloud_download_path: "{% if owncloud_release_channel == 'testing' %}/testing{% endif %}"
- name: create owncloud directory
  file:
    state: directory
    path: "{{ owncloud_root_directory }}"
    owner: root
    group: "{{ owncloud_web_user }}"
- name: ensure owncloud is downloaded
  command: curl -L "{{ owncloud_tarball_url }}{{ owncloud_version }}.{{ owncloud_tarball_extension }}" \
          -o "/tmp/owncloud_tarball.{{ owncloud_tarball_extension }}"
  args:
    creates: "/tmp/owncloud_tarball.{{ owncloud_tarball_extension }}"

- name: ensure owncloud is installed
  unarchive:  
    src: "/tmp/owncloud_tarball.{{ owncloud_tarball_extension }}"
    dest: "{{ nginx_root_directory }}"
    copy: no
  when: "owncloud_installed != true or owncloud_installed_version != owncloud_version"
  register: owncloud_download
  