- hosts: localhost
  roles:
    - openstack/create_instance
  vars:
    instance_hostname: portal.hispacloud.allinone
    instance_security_group: portal_hispacloud
    instance_size: 589
    instance_network: ext-net