## Install owncloud node

- hosts: default
  user: debian
  become: yes
  roles:
    - provisioning/minimal_packages
    - provisioning/populate_users
    - provisioning/sysconfig
    - nginx
    - php
    - mariadb
    # - owncloud