## Install owncloud node

- hosts: all
  become: yes
  roles:
    - provisioning/minimal_packages
    - provisioning/populate_users
    - provisioning/sysconfig
    - nginx
    - php
    - mariadb
    - ssl-certs
    - owncloud