---
- name: Install selinux python module
  become: yes
  yum: name=policycoreutils-python  state=latest

- name: add owncloud selinux policies
  command: semanage fcontext -a -t httpd_sys_rw_content_t {{ item }}
  with_items:
    - '{{ owncloud_root_directory }}/data'
    - '{{ owncloud_root_directory }}/config'
    - '{{ owncloud_root_directory }}/apps'
  tags: selinux
  
- name: restorecon  owncloud selinux policies
  command: restorecon -r {{ item }}
  with_items:
    - '{{ owncloud_root_directory }}/data'
    - '{{ owncloud_root_directory }}/config'
    - '{{ owncloud_root_directory }}/apps'
  tags: selinux
